### ISSUE TITLE
Can't change configuration in Tools.

### ISSUE THREAD

**Issue by SilentAqua** [HJLebbink/asm-dude#108]
Sorry for bothering but I have problem with changing settings and I couldn't find solution for my problem anywhere. Few years ago I installed AsmDude on VS 2015 and it worked without problem. Though I have problem with it on VS 2017 or 2019. When I click on AsmDude or AsmDude->General it's either just showing me blank black space in settings window or just crashes VS completely. Does somebody maybe know how to fix my VS? I worked on different computer and there AsmDude works without problem but on every Visual that has my account linked I have this problem.

**Comment by HJLebbink** [comment]
The only thing that springs to mind is that the latests AsmDude uses .NET framework 4.8; this will be installed automatically when AsmDude is installed (by vs), but that install may have gone wrong. You could check whether that is installed on your machine. Or that an older settings file exists that (somehow) did not got overwritten with a newer settings file when upgrading AsmDude. I assume you did a clean install of vs2019 and installed AsmDude, then no such settings issue could occur (I guess). If you find out what it was, do let me know.

**Comment by udenhat** [comment]
I have experienced the same issue with the black screen in Tools->Options->AsmDude.
Worked perfectly in vs2015, but not in vs2019 on same machine. Clean install of vs2019 and AsmDude.

AsmDude reports the following error:
`Welcome to
 _____             ____        _     
|  _  |___ _____  |    \ _ _ _| |___ 
|     |_ -|     | |  |  | | | . | -_|
|__|__|___|_|_|_| |____/|___|___|___|
INFO: Loaded AsmDude version 1.9.6.14 (29-09-2019 20:26:34)
INFO: Open source assembly extension. Making programming in assembler almost bearable.
INFO: More info at https://github.com/HJLebbink/asm-dude 
----------------------------------
ERROR: AsmDude.Squiggles.SquigglesTagger:Update_Error_Tasks_Labels_Async; e=System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber, Span& extent, Int32& lineBreakLength)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at AsmDude.Squiggles.SquigglesTagger.<Update_Error_Tasks_Labels_Async>b__21_0() in C:\Users\henk\Documents\Github\asm-dude\VS\CSHARP\asm-dude-vsix\Squiggles\SquigglesTagger.cs:line 708
`

Hope this can help solve the issue for this fantastic tool.
