### ISSUE TITLE
Known issue AsmDude2: unable to communicate with LSP on Windows 10

### ISSUE THREAD

**Issue by HJLebbink** [HJLebbink/asm-dude#146]
Known issue: AsmDude2 communicates with the LSP with pipes (https://learn.microsoft.com/en-us/windows/win32/ipc/pipes), this works nicely on all windows 11 machines I could my hands on. On the one Windows 10 machine I still have, whatever I try I keep hitting the following issue. 

![image](https://github.com/HJLebbink/asm-dude/assets/1561352/01b013c7-230d-4e4d-a349-34d65a6b5fb2)

If anyone knows a solution, do let me know!

**Comment by maddinthegreat** [comment]
I have Windows 11 and it doesn't work.

---------------------------
Microsoft Visual Studio
---------------------------
AsmDude2 Language Server Protocol (LSP) failed to activate.
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.

   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)

   at System.Security.Principal.NTAccount.Translate(Type targetType)

   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)

   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)

   at AsmDude2.AsmLanguageClient.<ActivateAsync>d__23.MoveNext() in C:\Source\Github\asm-dude\VS\CSHARP\asm-dude2-vsix\AsmLanguageClient.cs:line 269

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.LanguageServer.Cl...
---------------------------
OK   
---------------------------

**Comment by maddinthegreat** [comment]
Looks you must have admin rights! No good programming practice.

**Comment by LeonsCodeLab** [comment]
Exactly the same for me.

**Comment by HJLebbink** [comment]
Still no help from Microsoft on this, and I'm at a loss what can cause it. I can easily reproduce the issue on one of my development machines, wasted more than 30 hours on trying to fix it. I'm sorry, I'm only an assembly programmer... not an Windows 10 internals hacker...

**Comment by MickeyNT** [comment]
Maybe this info helps you
The user group "Everyone" doesn't exist on my German Windows 11. So if I create the new group "Everyone" and add the "Jeder" group into it the above exception will be no more thrown. Unfortunately the syntax highlighting still doesn't work ..

**Comment by HJLebbink** [comment]
The thing is, these security and authentication details have changed between 10 and windows 11 (it seems), and nobody seems to care to figure this out for old windows versions.

**Comment by MickeyNT** [comment]
Hi @HJLebbink,

today I had a little bit time to try out the solution using SecurityIdentifier instead of named groups for creating PipeAccessRule(s).
It seems it works well (I also see the communication between VS 2022 and AsmDude2.LSP.exe) so I would just share my changes here. In the files

\repos\asm-dude\VS\CSHARP\asm-dude2-vsix\AsmLanguageClient.cs and
\repos\asm-dude\VS\CSHARP\asm-dude2-ls\Worker.cs

create PipeAccessRule as follows:
``
        SecurityIdentifier everyone = new SecurityIdentifier(WellKnownSidType.WorldSid, null);
        PipeAccessRule pipeAccessRule = new(everyone, PipeAccessRights.ReadWrite, System.Security.AccessControl.AccessControlType.Allow);
        ``
I had trouble with the preview version of the MS LanguageServer packages so I made my changes based on
https://github.com/HJLebbink/asm-dude/commit/2b897a0fac8afda4f27f5612bc228e5a3e43d41

Regards from Stuttgart

**Comment by HJLebbink** [comment]
Thank you for your time; I'll look at it tonight straight away.

**Comment by HJLebbink** [comment]
@MickeyNT, thanx this seems to have fixed the issue for my windows 10 setup, i hope this will also fix it for those other users out there. Great thanx! See https://github.com/HJLebbink/asm-dude/releases/tag/v2.0.1.0

**Comment by Nespelem-3000** [comment]
It works!
![asm_dude_win_10_fixed](https://github.com/HJLebbink/asm-dude/assets/88687653/3d1f5e49-0ce8-43da-b8cf-575f197819d2)

**Comment by HJLebbink** [comment]
> It works!
That is good news! TY for the update.

**Comment by lstrsrt** [comment]
Unfortunately still having this issue on 21H2 (19044). This error always comes up after a couple of minutes. I'll install a 22H2 VM tomorrow and see if it works there.

![Pwcf0XvEYu_cropped](https://github.com/HJLebbink/asm-dude/assets/79076531/50e59922-00a9-4084-9533-862a6ca68e60)

**Comment by Kule02** [comment]
It's also not working for me on Windows 10 Pro 22H2 OS build: 19045.3996. I'm not sure how to provide anything that could help narrow it down or fix it myself. I get the same message as lstrsrt along with this pop up in the bottom left.

![Screenshot 2024-02-28 150801](https://github.com/HJLebbink/asm-dude/assets/53354698/ae88356d-0e1f-4387-968f-2b17e16af94d)

**Comment by bastiel** [comment]
@HJLebbink I noticed that the highlighting settings work for everything except the registers. If I edit the colors or enable the italicization for the regiters, I'll get an LSP failed to activate error, but mine is because the path to AsmDude's LSP.exe was denied.  

I've ran VS Studio as an admin and even installed via the Github installer but the errors are the same. It seems to be inconsistent for me because it'll work randomly on different W10 machines while others give the error.

**Comment by HJLebbink** [comment]
@Kule02

> It's also not working for me on Windows 10 Pro 22H2 OS build: 19045.3996. I'm not sure how to provide anything that could help narrow it down or fix it myself. I get the same message as lstrsrt along with this pop up in the bottom left.

I didn't keep track of the windows versions that did not work for me (which would have been useful to understand the cause), but my working setup currently has 19045.4046. It must be some optional component that fixes or breaks this. Thus, you have the LSP running but connection to it times out?

**Comment by HJLebbink** [comment]
@bastiel I think the error "LSP failed to activate" is because the LSP could not start. You say that it works on some W10 boxes but not on others, On the machines that it does not work, is the LSP running, if not, is it even installed? 

Everybody thanx for helping out. This is a nice example of "Hidden Windows Costs..."

**Comment by Kule02** [comment]
@HJLebbink I updated to 19045.4046 but still no luck. The syntax highlighting (mostly) works, like bastiel mentioned. I tried disabling the syntax highlighting to see if anything would happen and I got this error: 

![Screenshot 2024-02-29 115433](https://github.com/HJLebbink/asm-dude/assets/53354698/10388ea9-45ce-4b5f-89b4-5e8a40665057)

If I leave the extension to timeout, it displays these errors:

![Screenshot 2024-02-29 121559](https://github.com/HJLebbink/asm-dude/assets/53354698/9663de5c-8dd7-4451-b1c3-2d0ccf45f121)

![Screenshot 2024-02-29 121706](https://github.com/HJLebbink/asm-dude/assets/53354698/73a40466-6cfb-4b11-87f1-a6c45de96d15)

**Comment by MickeyNT** [comment]
Hi,
On my old PC I have the German Windows 10 Home / 22H2 19045.4046. I have just installed VS 2022 and the current version of AsmDude2. The syntax highlighting works but after some time the above error message will be displayed. I can help to solve the issue however I could not find the LSP version 17.8.9-preview. How can I download it?
I would create a debug version and check the errors with it....

**Comment by Sudsey** [comment]
Chiming in. On version 2.0.1.0, I get syntax highlighting, but no help-on-hover or suggestions. After a few minutes I get the same "AsmDude2 Language Server Protocol (LSP) failed to activate. ..." error as reported above. Windows 11 Home 23H2 22631.3155. Happy to pull out any logs or perform troubleshooting requested.

**Comment by Yogurt4** [comment]
Still having this problem.
Windows 10 22H2 19045.4123, VS Community 2022 (64-bit) 17.9.1, Asmdude2.v2-0-1-0
(By the way, why still 2.0.0.4 is the "latest" here while you can download 2.0.1.0 from the VS Marketplace?)

The same error as for @Kule02.

**Comment by bastiel** [comment]
> @bastiel I think the error "LSP failed to activate" is because the LSP could not start. You say that it works on some W10 boxes but not on others, On the machines that it does not work, is the LSP running, if not, is it even installed?

Sorry for the late reply @HJLebbink. I wasn't able to check this, but I installed .NET 7 Desktop Runtime like @Sudsey. The error no longer pops up, and some features like code folding and register highlighting even work now - but like @Sudsey, code completion doesn't work. 

Initially, after install .NET 7, everything but the code completion and register highlighting didn't work. I changed Assembly Flavour to "Auto Detect" from Intel MASM, and the register highlighting works now. But as previously mentioned, code completion does not.

**Comment by ghost** [comment]
I installed .NET 9 Desktop and still getting the LSP failure.  The MASM highlighting is working if I select both choices to MASM since I am writing that code x86-64.

** Is there a way to turn off the LSP so I just get the syntax highlight (for MASM)?? **

If you know how to turn off the constant LSP failure pop ups I would like to know that, thanks!

**Comment by vault-thirteen** [comment]
I am having a similar issue. The text is a bit different but it is also about LSP.

![ASM-Dude](https://github.com/HJLebbink/asm-dude/assets/54213347/10f4b9ee-96ff-4296-aed2-4d86aa2c0499)

Windows 10 22H2 19045.4412.
Visual Studio Community 2022 17.9.7.
AsmDude2 2.0.1.0.

**Comment by drewber78** [comment]
Is anyone still having this issue with W11? Just downloaded VS for a class and was trying to make ASMDude work per the class instructions, and it did for a minute, then gave me the long LSP failed to activate error everyone else has posted before. Thanks!

**Comment by henkjan-sneller** [comment]
I haven't tried the latest updates from ms in the last half year. Maybe
things got better. I'll give this horror story another try.

**Comment by dwtweilai** [comment]
It has a language server protocol (LSP) error in the latest version of Visual Studio 17.12.0, and unfortunately this plug-in is not working properly

**Comment by MarcinBrodka** [comment]
![vserror](https://github.com/user-attachments/assets/c47d3078-92b0-4829-a4b0-507464943925)
Windows 11, 23H2 22631.4460
Microsoft Visual Studio Community 2022 (64-bitowy) - Current
Version 17.12.3

**Comment by RayKoopa** [comment]
Reporting a similar UnauthorizedAccessException issue on
Windows 11 Education 24H2 (10.0.26100.2894) en-US
VS 2022 (64-bit) 17.13.0 Preview 2.1

Note that OPs "IdentityNotMapped" exception probably has other reasons stated above.

An event log entry showed the reason:
```
Description: A .NET application failed.
Application: AsmDude2.LSP.exe
Path: C:\Users\Ray\appdata\local\microsoft\visualstudio\17.0_37960112\extensions\54mawimu.vss\Server\AsmDude2.LSP.exe
Message: You must install or update .NET to run this application.

App: C:\Users\Ray\appdata\local\microsoft\visualstudio\17.0_37960112\extensions\54mawimu.vss\Server\AsmDude2.LSP.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  3.1.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  9.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

So as mentioned by others, installing the [.NET 7 Desktop Runtime (x64)](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.20-windows-x64-installer) was required to fix this in my case.

Register highlighting also didn't work until set to "Auto Detect", though it still seems to miss coloring some directives.
