### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by maddinthegreat** [HJLebbink/asm-dude#149]
---------------------------
Microsoft Visual Studio
---------------------------
AsmDude2 Language Server Protocol (LSP) failed to activate.
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.

   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)

   at System.Security.Principal.NTAccount.Translate(Type targetType)

   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)

   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)

   at AsmDude2.AsmLanguageClient.<ActivateAsync>d__23.MoveNext() in C:\Source\Github\asm-dude\VS\CSHARP\asm-dude2-vsix\AsmLanguageClient.cs:line 269

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.LanguageServer.Cl...
---------------------------
OK   
---------------------------

**Comment by maddinthegreat** [comment]
Already acknowledged by the CEO!
