### ISSUE TITLE
Crash in SquigglesTagger with Assembly Simulator enabled

### ISSUE THREAD

**Issue by MulleDK19** [HJLebbink/asm-dude#60]
System.ArgumentException: Value does not fall within the expected range.

```cpp
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.TaskProvider.Refresh()
   at Microsoft.VisualStudio.Shell.TaskProvider.TaskCollection.Add(Task task)
   at AsmDude.Squiggles.SquigglesTagger.<>c__DisplayClass19_0.<AddErrorTask_Redundant_Instruction_Async>b__0() in H:\Dropbox\sc\GitHub\asm-dude\VS\CSHARP\asm-dude-vsix\Squiggles\SquigglesTagger.cs:line 570
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AsmDude.Squiggles.SquigglesTagger.<AddErrorTask_Redundant_Instruction_Async>d__19.MoveNext() in H:\Dropbox\sc\GitHub\asm-dude\VS\CSHARP\asm-dude-vsix\Squiggles\SquigglesTagger.cs:line 557
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()```

**Comment by HJLebbink** [comment]
Thanks for reporting this. I'll look into it.

**Comment by HJLebbink** [comment]
I've added try-catches to prevent the problem from escalating. I could not reproduce the problem but it likely has something to do with multiple threads updating the error list.
